-- CreateTable
CREATE TABLE `Organization` (
    `ID` VARCHAR(191) NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Team` (
    `ID` VARCHAR(191) NOT NULL,
    `ORGANIZATION_ID` VARCHAR(191) NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `SLUG` VARCHAR(191) NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `ID` VARCHAR(191) NOT NULL,
    `ORGANIZATION_ID` VARCHAR(191) NOT NULL,
    `TEAM_ID` VARCHAR(191) NOT NULL,
    `LOGIN` VARCHAR(191) NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Repository` (
    `ID` VARCHAR(191) NOT NULL,
    `OWNER_USER_ID` VARCHAR(191) NULL,
    `OWNER_ORGANIZATION_ID` VARCHAR(191) NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `URL` VARCHAR(191) NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PullRequest` (
    `ID` VARCHAR(191) NOT NULL,
    `AUTHOR_ID` VARCHAR(191) NOT NULL,
    `REPO_ID` VARCHAR(191) NOT NULL,
    `MERGED_AT` DATETIME(3) NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Review` (
    `ID` VARCHAR(191) NOT NULL,
    `AUTHOR_ID` VARCHAR(191) NOT NULL,
    `PULLREQ_ID` VARCHAR(191) NOT NULL,
    `STATE` VARCHAR(191) NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ReviewComment` (
    `ID` VARCHAR(191) NOT NULL,
    `REVIEW_ID` VARCHAR(191) NOT NULL,
    `AUTHOR_ID` VARCHAR(191) NOT NULL,
    `TEXT` VARCHAR(191) NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Commit` (
    `ID` VARCHAR(191) NOT NULL,
    `AUTHOR_ID` VARCHAR(191) NOT NULL,
    `PULLREQ_ID` VARCHAR(191) NOT NULL,
    `ADDITIONS` INTEGER NOT NULL,
    `DELETIONS` INTEGER NOT NULL,
    `TIMESTAMP` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Team` ADD CONSTRAINT `Team_ORGANIZATION_ID_fkey` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `Organization`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ORGANIZATION_ID_fkey` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `Organization`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_TEAM_ID_fkey` FOREIGN KEY (`TEAM_ID`) REFERENCES `Team`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Repository` ADD CONSTRAINT `Repository_OWNER_USER_ID_fkey` FOREIGN KEY (`OWNER_USER_ID`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Repository` ADD CONSTRAINT `Repository_OWNER_ORGANIZATION_ID_fkey` FOREIGN KEY (`OWNER_ORGANIZATION_ID`) REFERENCES `Organization`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PullRequest` ADD CONSTRAINT `PullRequest_AUTHOR_ID_fkey` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PullRequest` ADD CONSTRAINT `PullRequest_REPO_ID_fkey` FOREIGN KEY (`REPO_ID`) REFERENCES `Repository`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Review` ADD CONSTRAINT `Review_AUTHOR_ID_fkey` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Review` ADD CONSTRAINT `Review_PULLREQ_ID_fkey` FOREIGN KEY (`PULLREQ_ID`) REFERENCES `PullRequest`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ReviewComment` ADD CONSTRAINT `ReviewComment_REVIEW_ID_fkey` FOREIGN KEY (`REVIEW_ID`) REFERENCES `Review`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ReviewComment` ADD CONSTRAINT `ReviewComment_AUTHOR_ID_fkey` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Commit` ADD CONSTRAINT `Commit_AUTHOR_ID_fkey` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Commit` ADD CONSTRAINT `Commit_PULLREQ_ID_fkey` FOREIGN KEY (`PULLREQ_ID`) REFERENCES `PullRequest`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;