name: Nodejs Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  nodetest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org
          scope: "@octocat"
      - run: npm install
      - run: npm install -g jest
      - run: npm run prisma:generate
      - run: npm run test:unit
